name: flutter_sentry_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sentry_flutter: ^9.16.1

dev_dependencies:
  sentry_dart_plugin: ^3.2.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: tot-d2
